### rest client - vscode extension

http://localhost:3000

###

http://localhost:3000/hello/john

###

POST http://localhost:3000/hello
Content-Type: application/x-www-form-urlencoded

first=john&last=doe

###

http://localhost:3000/hello/john?mode=shout

###

http://localhost:3000/html

###

http://localhost:3000/jsx

###

http://localhost:3000/admin
Authorization: Basic admin:admin

###

http://localhost:3000/robots.txt
